name: Hello with Date

on:
  push:
    branches: [main]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Set TODAY variable
        run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV

      - name: Greet
        run: echo "Hello world, today is $TODAY"
